V={
"ACS Mixed Martial Arts":("CONFIRMED","","Still 301s to Chinese corporate site, hijack live"),
"Black Flag Submission Co.":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Brandon Abdullah's Martial Arts and Fitness":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Brazilian Jiu-Jitsu Academy of Tacoma (Marcello C. Monteiro)":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Bridge City Combat":("CONFIRMED","","aaeamerica.com is Against All Enemies Armory, firearms"),
"Bristol BJJ":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Bwarrior MMA":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Cannon Brazilian Jiu-Jitsu":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Coastal Combatives":("CONFIRMED","","Bluehost placeholder parking page, no school content"),
"Courage Honor Strength Brazilian Jiu-Jitsu":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Crossfit 585 BJJ":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Curtis Tillman's Mixed Martial Arts Academy":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"East West MMA":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Ephrata Martial Arts":("CONFIRMED","","Live but striking only: sanshou, kickboxing, boxing, muay thai"),
"Fight-Sport Training Center":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"GB Dana Point":("CONFIRMED","","graciebarra.com/dana-point-ca returns Page not found"),
"Gracie Barra North Babylon":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Gracie Jiu-Jitsu Point Lookout":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Guerrero BJJ & MMA":("CONFIRMED","","Redirects to njkick.com, No Limit Martial Arts West Orange"),
"JG Monster Jiujitsu Fitness":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Kfm Martial Arts & Fitness Academy":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Labrador City BJJ":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Montpelier BJJ":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Peloton Martial Arts Center":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Presque Isle BJJ":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Refit Academy - Wynwood":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Samuel Puccio Brazilian Jiu-Jitsu":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Souris Brazilian Jiu-Jitsu":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Touro Fajardo Brazilian Jiu Jitsu":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Utica Combat Athletics":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
"Yojimbo BJJ":("CONFIRMED_DEAD","","NXDOMAIN (Status 3) both apex and www"),
'Checkmat Phoenix':('CONFIRMED_DEAD', '', 'SERVFAIL then NXDOMAIN in browser, no site'),
"Kokopelli's Gym":('CONFIRMED_DEAD', '', 'SERVFAIL then NXDOMAIN in browser, no site'),
'Northern Colorado Jiu Jitsu':('CONFIRMED_DEAD', '', 'SERVFAIL then NXDOMAIN in browser, no site'),
"Eric Nolan's Xtreme Training Center":('CONFIRMED_DEAD', '', 'SERVFAIL then NXDOMAIN in browser, no site'),
'Ronin Martial Arts - Westport':('CONFIRMED_DEAD', '', 'SERVFAIL then NXDOMAIN in browser, no site'),
'SLL Grappling Academy - Brazilian Jiu-Jitsu (BJJ)':('CONFIRMED_DEAD', '', 'SERVFAIL then NXDOMAIN in browser, no site'),
'CrossFit Arsenal (and BJJ)':('CONFIRMED_DEAD', '', 'No A record, NXDOMAIN in browser'),
'Nexus Martial Arts & Fitness':('CONFIRMED_DEAD', '', 'No A record, NXDOMAIN in browser'),
'New Wave Martial Arts Perry Hall':('CONFIRMED_DEAD', '', 'No A record, NXDOMAIN in browser'),
'The Desert Dojo':('CONFIRMED_DEAD', '', 'No A record, NXDOMAIN in browser'),
'TeckHit Boxing, Kickboxing, & MMA Gym':('CONFIRMED_DEAD', '', 'No A record, NXDOMAIN in browser'),
'Infinite Fighting Concepts MMA':('CONFIRMED', '', 'Namecheap just-registered parking page with domain auctions'),
'Jg Academy Manteca':('CONFIRMED', '', 'JG Academy live but /manteca 404s, only Brentwood CA remains'),
'Kifaru Jitsu Academy of Martial Arts':('UNSURE', '', 'Cloudflare error 1001, origin DNS broken, no content readable'),
'Longo and Weidman MMA':('CONFIRMED', '', 'NameBright coming-soon parking page'),
'Madera Martial Arts':('CONFIRMED', '', 'Namecheap just-registered parking page with auctions'),
'Master Gauss Martial Arts Center':('CONFIRMED', '', 'Live Modern Arnis stick-fighting school, no grappling offered'),
'Marcelo Garcia Academy LA':('CHANGED', '', 'Now redirects to marcelogarciajj.com, only NYC and Hawaii'),
'Michigan Sports Camps':('CHANGED', '', 'ttsfitness.com now 404s and www unreachable, no site'),
'Relentless Martial Arts':('UNSURE', '', 'DNS resolves, apex will not render, www refuses connection'),
'Ronin Jiu-Jitsu North Las Vegas':('CONFIRMED', '', 'roninbjj.org is Ronin Jiu-Jitsu Attleboro MA, different school'),
'Spartan Team Brazilian Jiu-Jitsu':('CONFIRMED', '', 'Spartan Boxing Gym Medford OR, boxing only, no grappling'),
'The Dojo LLC':('CONFIRMED', '', 'Still serves Chinese Kaiyun gambling/ICT site, hijack live'),
'Summerlin BJJ':('CONFIRMED', '', 'Bluehost placeholder page, not a school site'),
'Westchester Mixed Martial Arts & Fitness':('CONFIRMED', '', 'Redirects to HugeDomains for-sale lander, $95'),
'Hartford Dojo':('CHANGED', '', 'gracieacademy.com now fails to load on http and https'),
'UFC GYM East Rutherford':('CONFIRMED', '', 'Location page redirects to generic /locations index'),
'UFC GYM Lancaster':('CONFIRMED', '', 'Location page returns PAGE NOT FOUND'),
'UFC GYM McAllen':('CONFIRMED', '', 'Location page returns PAGE NOT FOUND'),
'UFC GYM Orange':('CONFIRMED', '', 'Location page redirects to generic /locations index'),
'UFC GYM Sacramento':('CONFIRMED', '', 'Location page returns PAGE NOT FOUND'),
'UFC GYM Winter Springs':('CONFIRMED', '', 'Location page returns PAGE NOT FOUND'),
'UFC Gym Oceanside':('CONFIRMED', '', 'Location page redirects to generic /locations index'),
'Advantage BJJ Martial Arts & Fitness':('CONFIRMED', '', 'Domain now serves Lockhart Jiu Jitsu, a different school'),
'REAL WORLD MMA & Fitness':('UNSURE', '', 'Invalid TLS cert blocks page, content unreadable'),
'Stamford Judo':('UNSURE', '', 'Resolves but error page on http and https, apex and www'),
}
